import type { AdminProduct, MainCategory, SubCategory } from "../types/product";

export const SAMPLE_MAIN_CATEGORIES: MainCategory[] = [
  { id: "cat-1", name: "Electronics", slug: "electronics", isActive: true, subCount: 4 },
  { id: "cat-2", name: "Fashion", slug: "fashion", isActive: true, subCount: 3 },
  { id: "cat-3", name: "Home & Kitchen", slug: "home-kitchen", isActive: true, subCount: 2 },
  { id: "cat-4", name: "Sports", slug: "sports", isActive: true, subCount: 2 },
];

export const SAMPLE_SUB_CATEGORIES: SubCategory[] = [
  { id: "sub-1", name: "Mobiles", slug: "mobiles", parentId: "cat-1", parentName: "Electronics", isActive: true },
  { id: "sub-2", name: "Laptops", slug: "laptops", parentId: "cat-1", parentName: "Electronics", isActive: true },
  { id: "sub-3", name: "TVs", slug: "tvs", parentId: "cat-1", parentName: "Electronics", isActive: true },
  { id: "sub-4", name: "Headphones", slug: "headphones", parentId: "cat-1", parentName: "Electronics", isActive: true },
  { id: "sub-5", name: "Men's Clothing", slug: "mens-clothing", parentId: "cat-2", parentName: "Fashion", isActive: true },
  { id: "sub-6", name: "Women's Clothing", slug: "womens-clothing", parentId: "cat-2", parentName: "Fashion", isActive: true },
  { id: "sub-7", name: "Furniture", slug: "furniture", parentId: "cat-3", parentName: "Home & Kitchen", isActive: true },
  { id: "sub-8", name: "Kitchen Appliances", slug: "kitchen-appliances", parentId: "cat-3", parentName: "Home & Kitchen", isActive: true },
];

export const SAMPLE_PRODUCTS: AdminProduct[] = [
  {
    id: "prod-1",
    name: "Samsung Galaxy S24 128GB",
    brand: "Samsung",
    sku: "SAM-S24-128",
    categoryId: "cat-1",
    categoryName: "Electronics",
    subCategoryId: "sub-1",
    subCategoryName: "Mobiles",
    shortDescription: "Flagship smartphone with 50MP camera and 120Hz display.",
    longDescription: "The Samsung Galaxy S24 features a stunning 6.2-inch Dynamic AMOLED display, Exynos 2400 chipset, and a versatile triple camera system. Perfect for productivity and entertainment.",
    mrp: 79999,
    sellingPrice: 69999,
    discountPercent: 12,
    imageUrls: [
      "https://images.pexels.com/photos/47261/pexels-photo-47261.jpeg?auto=compress",
    ],
    specifications: { Color: "Phantom Black", RAM: "8 GB", Storage: "128 GB", Display: "6.2 inch" },
    stock: 150,
    status: "active",
  },
  {
    id: "prod-2",
    name: "Apple MacBook Air M2",
    brand: "Apple",
    sku: "APL-MBA-M2",
    categoryId: "cat-1",
    categoryName: "Electronics",
    subCategoryId: "sub-2",
    subCategoryName: "Laptops",
    shortDescription: "Thin and light laptop with M2 chip.",
    longDescription: "MacBook Air with the M2 chip delivers incredible performance and battery life in a fanless design. Ideal for students and professionals.",
    mrp: 114900,
    sellingPrice: 104900,
    discountPercent: 9,
    imageUrls: [
      "https://images.pexels.com/photos/205421/pexels-photo-205421.jpeg?auto=compress",
    ],
    specifications: { Chip: "M2", RAM: "8 GB", SSD: "256 GB", Display: "13.6 inch" },
    stock: 45,
    status: "active",
  },
  {
    id: "prod-3",
    name: "Sony WH-1000XM5 Wireless Headphones",
    brand: "Sony",
    sku: "SON-WH1000XM5",
    categoryId: "cat-1",
    categoryName: "Electronics",
    subCategoryId: "sub-4",
    subCategoryName: "Headphones",
    shortDescription: "Industry-leading noise cancellation.",
    longDescription: "Experience premium sound quality with Sony's best noise-cancelling headphones. 30-hour battery, multipoint connection, and touch controls.",
    mrp: 29990,
    sellingPrice: 24990,
    discountPercent: 17,
    imageUrls: [
      "https://images.pexels.com/photos/3394650/pexels-photo-3394650.jpeg?auto=compress",
    ],
    specifications: { Color: "Black", "Driver Size": "30 mm", "Battery": "30 hrs", "Bluetooth": "5.2" },
    stock: 80,
    status: "active",
  },
  {
    id: "prod-4",
    name: "Cotton Casual T-Shirt (Men)",
    brand: "Generic",
    sku: "GEN-TSHIRT-M",
    categoryId: "cat-2",
    categoryName: "Fashion",
    subCategoryId: "sub-5",
    subCategoryName: "Men's Clothing",
    shortDescription: "Comfortable cotton t-shirt for everyday wear.",
    longDescription: "Made from 100% organic cotton, this t-shirt is soft, breathable, and available in multiple colors. Regular fit.",
    mrp: 999,
    sellingPrice: 599,
    discountPercent: 40,
    imageUrls: [
      "https://images.pexels.com/photos/1040945/pexels-photo-1040945.jpeg?auto=compress",
    ],
    specifications: { Material: "100% Cotton", Fit: "Regular", "Care": "Machine Wash" },
    stock: 500,
    status: "active",
  },
  {
    id: "prod-5",
    name: "Non-Stick Cookware Set 5 Pcs",
    brand: "Prestige",
    sku: "PRES-COOK-5",
    categoryId: "cat-3",
    categoryName: "Home & Kitchen",
    subCategoryId: "sub-8",
    subCategoryName: "Kitchen Appliances",
    shortDescription: "Durable non-stick cookware set for daily cooking.",
    longDescription: "Includes kadai, fry pan, tawa, and lids. PFOA-free non-stick coating, suitable for gas and induction.",
    mrp: 2999,
    sellingPrice: 1999,
    discountPercent: 33,
    imageUrls: [
      "https://images.pexels.com/photos/4226806/pexels-photo-4226806.jpeg?auto=compress",
    ],
    specifications: { "Set Contents": "5 Pcs", Material: "Aluminum", "Induction": "Yes" },
    stock: 120,
    status: "active",
  },
];
