import type { Deal } from "../types/deal";

const baseImage = (seed: string) => `https://picsum.photos/seed/${seed}/400/400`;

/**
 * Halloween-themed dummy deals
 */
export const HALLOWEEN_DEALS: Deal[] = [
  {
    id: "h1",
    title: "Halloween Costume Kids Ghost Outfit",
    price: 12.99,
    originalPrice: 24.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("halloween1"),
    postedAt: "2026-01-02T10:00:00",
    category: "Halloween Deals",
    url: "#",
    discount: 48,
    isHotDeal: true,
  },
  {
    id: "h2",
    title: "Pumpkin Carving Kit 10-Piece Set",
    price: 8.49,
    originalPrice: 14.99,
    merchant: "Target",
    imageUrl: baseImage("halloween2"),
    postedAt: "2026-01-02T09:30:00",
    category: "Halloween Deals",
    url: "#",
    discount: 43,
  },
  {
    id: "h3",
    title: "Halloween LED String Lights 100ct",
    price: 15.99,
    originalPrice: 29.99,
    merchant: "Wayfair",
    imageUrl: baseImage("halloween3"),
    postedAt: "2026-01-02T09:00:00",
    category: "Halloween Deals",
    url: "#",
    discount: 47,
  },
  {
    id: "h4",
    title: "Assorted Halloween Candy Mix 5lb Bag",
    price: 14.99,
    originalPrice: 22.99,
    merchant: "Walmart.com",
    imageUrl: baseImage("halloween4"),
    postedAt: "2026-01-02T08:45:00",
    category: "Halloween Deals",
    url: "#",
    discount: 35,
  },
  {
    id: "h5",
    title: "Adult Witch Costume Deluxe",
    price: 29.99,
    originalPrice: 49.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("halloween5"),
    postedAt: "2026-01-02T08:00:00",
    category: "Halloween Deals",
    url: "#",
    discount: 40,
    isHotDeal: true,
  },
  {
    id: "h6",
    title: "Haunted House Decoration Set",
    price: 34.99,
    originalPrice: 59.99,
    merchant: "Spirit Halloween",
    imageUrl: baseImage("halloween6"),
    postedAt: "2026-01-02T07:30:00",
    category: "Halloween Deals",
    url: "#",
    discount: 42,
  },
];

/**
 * Wayfair-specific dummy deals
 */
export const WAYFAIR_DEALS: Deal[] = [
  {
    id: "w1",
    title: "Wayfair Way Day Sale: Up to 80% Off Sitewide",
    price: 0,
    originalPrice: 0,
    merchant: "Wayfair",
    imageUrl: baseImage("wayfair1"),
    postedAt: "2026-01-03T08:00:00",
    category: "Wayfair Deals",
    url: "#",
    description: "Save big during Wayfair's biggest sale of the year",
  },
  {
    id: "w2",
    title: "Modern 3-Seater Sofa with Tufted Back",
    price: 349.99,
    originalPrice: 549.99,
    merchant: "Wayfair",
    imageUrl: baseImage("wayfair2"),
    postedAt: "2026-01-03T07:30:00",
    category: "Wayfair Deals",
    url: "#",
    discount: 36,
    isHotDeal: true,
  },
  {
    id: "w3",
    title: "Solid Wood Dining Table 6-Seater",
    price: 299.99,
    originalPrice: 449.99,
    merchant: "Wayfair",
    imageUrl: baseImage("wayfair3"),
    postedAt: "2026-01-03T07:00:00",
    category: "Wayfair Deals",
    url: "#",
    discount: 33,
  },
  {
    id: "w4",
    title: "Queen Upholstered Platform Bed Frame",
    price: 249.99,
    originalPrice: 399.99,
    merchant: "Wayfair",
    imageUrl: baseImage("wayfair4"),
    postedAt: "2026-01-03T06:30:00",
    category: "Wayfair Deals",
    url: "#",
    discount: 38,
  },
  {
    id: "w5",
    title: "5-Drawer Dresser White",
    price: 199.99,
    originalPrice: 329.99,
    merchant: "Wayfair",
    imageUrl: baseImage("wayfair5"),
    postedAt: "2026-01-03T06:00:00",
    category: "Wayfair Deals",
    url: "#",
    discount: 39,
  },
  {
    id: "w6",
    title: "Outdoor Patio Dining Set 4-Piece",
    price: 449.99,
    originalPrice: 699.99,
    merchant: "Wayfair",
    imageUrl: baseImage("wayfair6"),
    postedAt: "2026-01-03T05:30:00",
    category: "Wayfair Deals",
    url: "#",
    discount: 36,
    isHotDeal: true,
  },
];

/**
 * Top retail (Amazon, Target, Walmart, etc.) dummy deals
 */
export const TOP_RETAIL_DEALS: Deal[] = [
  {
    id: "r1",
    title: "Apple AirPods Pro (2nd Generation)",
    price: 199.99,
    originalPrice: 249.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("retail1"),
    postedAt: "2026-01-03T09:15:00",
    category: "Top Retail Deals",
    url: "#",
    discount: 20,
    isHotDeal: true,
  },
  {
    id: "r2",
    title: "Ninja Foodi 9-in-1 Pressure Cooker",
    price: 149.99,
    originalPrice: 249.99,
    merchant: "Target",
    imageUrl: baseImage("retail2"),
    postedAt: "2026-01-03T09:00:00",
    category: "Top Retail Deals",
    url: "#",
    discount: 40,
  },
  {
    id: "r3",
    title: "Samsung 65\" QLED 4K Smart TV",
    price: 897.99,
    originalPrice: 1299.99,
    merchant: "Walmart.com",
    imageUrl: baseImage("retail3"),
    postedAt: "2026-01-03T08:45:00",
    category: "Top Retail Deals",
    url: "#",
    discount: 31,
    isHotDeal: true,
  },
  {
    id: "r4",
    title: "Dyson V15 Detect Cordless Vacuum",
    price: 499.99,
    originalPrice: 649.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("retail4"),
    postedAt: "2026-01-03T08:30:00",
    category: "Top Retail Deals",
    url: "#",
    discount: 23,
  },
  {
    id: "r5",
    title: "KitchenAid Artisan Stand Mixer 5Qt",
    price: 279.99,
    originalPrice: 429.99,
    merchant: "Target",
    imageUrl: baseImage("retail5"),
    postedAt: "2026-01-03T08:15:00",
    category: "Top Retail Deals",
    url: "#",
    discount: 35,
  },
  {
    id: "r6",
    title: "Nintendo Switch OLED Model",
    price: 299.99,
    originalPrice: 349.99,
    merchant: "Walmart.com",
    imageUrl: baseImage("retail6"),
    postedAt: "2026-01-03T08:00:00",
    category: "Top Retail Deals",
    url: "#",
    discount: 14,
    isHotDeal: true,
  },
];

/**
 * Tool deals (power tools, hand tools)
 */
export const TOOL_DEALS: Deal[] = [
  {
    id: "tool1",
    title: "DEWALT 20V Max Cordless Drill/Driver Kit",
    price: 99,
    originalPrice: 149,
    merchant: "Home Depot",
    imageUrl: baseImage("tool1"),
    postedAt: "2026-01-04T10:00:00",
    category: "Tool Deals",
    url: "#",
    discount: 34,
    isHotDeal: true,
  },
  {
    id: "tool2",
    title: "Craftsman 195-Piece Mechanic Tool Set",
    price: 79.99,
    originalPrice: 129.99,
    merchant: "Lowe's",
    imageUrl: baseImage("tool2"),
    postedAt: "2026-01-04T09:30:00",
    category: "Tool Deals",
    url: "#",
    discount: 38,
  },
  {
    id: "tool3",
    title: "Milwaukee M18 Fuel Impact Driver",
    price: 149,
    originalPrice: 199,
    merchant: "Amazon.com",
    imageUrl: baseImage("tool3"),
    postedAt: "2026-01-04T09:00:00",
    category: "Tool Deals",
    url: "#",
    discount: 25,
    isHotDeal: true,
  },
  {
    id: "tool4",
    title: "Kobalt 24-Volt Cordless Leaf Blower",
    price: 79,
    originalPrice: 119,
    merchant: "Lowe's",
    imageUrl: baseImage("tool4"),
    postedAt: "2026-01-04T08:30:00",
    category: "Tool Deals",
    url: "#",
    discount: 34,
  },
];

/**
 * Tech deals (laptops, gadgets, electronics)
 */
export const TECH_DEALS: Deal[] = [
  {
    id: "tech1",
    title: "Sony WH-1000XM5 Wireless Noise Canceling Headphones",
    price: 299.99,
    originalPrice: 399.99,
    merchant: "Best Buy",
    imageUrl: baseImage("tech1"),
    postedAt: "2026-01-04T10:00:00",
    category: "Tech Deals",
    url: "#",
    discount: 25,
    isHotDeal: true,
  },
  {
    id: "tech2",
    title: "Dell 16 Plus 16-in 2.5K Laptop w/Core Ultra 7, 1TB SSD",
    price: 799.99,
    originalPrice: 1149.99,
    merchant: "Dell.com",
    imageUrl: baseImage("tech2"),
    postedAt: "2026-01-04T09:30:00",
    category: "Tech Deals",
    url: "#",
    discount: 30,
    isHotDeal: true,
  },
  {
    id: "tech3",
    title: "Apple iPad Pro 12.9\" M4 Chip",
    price: 999,
    originalPrice: 1199,
    merchant: "Amazon.com",
    imageUrl: baseImage("tech3"),
    postedAt: "2026-01-04T09:00:00",
    category: "Tech Deals",
    url: "#",
    discount: 17,
  },
  {
    id: "tech4",
    title: "Samsung 65\" Class QLED 4K Smart TV",
    price: 799.99,
    originalPrice: 1299.99,
    merchant: "Samsung.com",
    imageUrl: baseImage("tech4"),
    postedAt: "2026-01-04T08:45:00",
    category: "Tech Deals",
    url: "#",
    discount: 38,
    isHotDeal: true,
  },
  {
    id: "tech5",
    title: "Google Pixel 8 Pro 256GB",
    price: 749,
    originalPrice: 999,
    merchant: "Google Store",
    imageUrl: baseImage("tech5"),
    postedAt: "2026-01-04T08:00:00",
    category: "Tech Deals",
    url: "#",
    discount: 25,
  },
  {
    id: "tech6",
    title: "Logitech MX Master 3S Wireless Mouse",
    price: 79.99,
    originalPrice: 99.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("tech6"),
    postedAt: "2026-01-04T07:30:00",
    category: "Tech Deals",
    url: "#",
    discount: 20,
  },
];

/**
 * Apparel deals (clothing, shoes, accessories)
 */
export const APPAREL_DEALS: Deal[] = [
  {
    id: "app1",
    title: "Adidas Mens Daily 3.0 Sneaker",
    price: 26,
    originalPrice: 55,
    merchant: "Amazon.com",
    imageUrl: baseImage("app1"),
    postedAt: "2026-01-04T10:00:00",
    category: "Apparel",
    url: "#",
    discount: 53,
    isHotDeal: true,
  },
  {
    id: "app2",
    title: "Crocs Mens and Womens Baya Clogs",
    price: 23.99,
    originalPrice: 49.99,
    merchant: "eBay",
    imageUrl: baseImage("app2"),
    postedAt: "2026-01-04T09:30:00",
    category: "Apparel",
    url: "#",
    discount: 52,
    isHotDeal: true,
  },
  {
    id: "app3",
    title: "Levi's 501 Original Straight Jeans",
    price: 39.99,
    originalPrice: 69.99,
    merchant: "Levi.com",
    imageUrl: baseImage("app3"),
    postedAt: "2026-01-04T09:00:00",
    category: "Apparel",
    url: "#",
    discount: 43,
  },
  {
    id: "app4",
    title: "Nike Dri-FIT Running Shorts",
    price: 24.99,
    originalPrice: 40,
    merchant: "Nike.com",
    imageUrl: baseImage("app4"),
    postedAt: "2026-01-04T08:30:00",
    category: "Apparel",
    url: "#",
    discount: 38,
    isHotDeal: true,
  },
  {
    id: "app5",
    title: "Carhartt Force Hooded Sweatshirt",
    price: 34.99,
    originalPrice: 59.99,
    merchant: "Target",
    imageUrl: baseImage("app5"),
    postedAt: "2026-01-04T08:00:00",
    category: "Apparel",
    url: "#",
    discount: 42,
  },
];

/**
 * Home deals (furniture, decor, appliances)
 */
export const HOME_DEALS: Deal[] = [
  {
    id: "home1",
    title: "Frigidaire 60-Pint Dehumidifier",
    price: 139.99,
    originalPrice: 499,
    merchant: "Woot.com",
    imageUrl: baseImage("home1"),
    postedAt: "2026-01-04T10:00:00",
    category: "Home Deals",
    url: "#",
    discount: 72,
    isHotDeal: true,
  },
  {
    id: "home2",
    title: "5-Outlet Mifaso 1080J Surge Protector w/ Night Light",
    price: 8,
    originalPrice: 13,
    merchant: "Amazon.com",
    imageUrl: baseImage("home2"),
    postedAt: "2026-01-04T09:30:00",
    category: "Home Deals",
    url: "#",
    discount: 38,
    isHotDeal: true,
  },
  {
    id: "home3",
    title: "Dyson V15 Detect Cordless Vacuum",
    price: 499.99,
    originalPrice: 649.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("home3"),
    postedAt: "2026-01-04T09:00:00",
    category: "Home Deals",
    url: "#",
    discount: 23,
  },
  {
    id: "home4",
    title: "Kobalt Stainless Steel 2pc Heavy-duty Scissors",
    price: 9.98,
    originalPrice: 14.99,
    merchant: "Lowes.com",
    imageUrl: baseImage("home4"),
    postedAt: "2026-01-04T08:45:00",
    category: "Home Deals",
    url: "#",
    discount: 33,
  },
  {
    id: "home5",
    title: "LEGO Botanicals Bouquet of Roses Artificial Flowers",
    price: 47.99,
    originalPrice: 59.99,
    merchant: "Amazon.com",
    imageUrl: baseImage("home5"),
    postedAt: "2026-01-04T08:00:00",
    category: "Home Deals",
    url: "#",
    discount: 20,
  },
];

/**
 * Travel deals (flights, hotels, packages)
 */
export const TRAVEL_DEALS: Deal[] = [
  {
    id: "trav1",
    title: "United Airlines Round-Trip to NYC",
    price: 99,
    originalPrice: 199,
    merchant: "United.com",
    imageUrl: baseImage("trav1"),
    postedAt: "2026-01-04T10:00:00",
    category: "Travel Deals",
    url: "#",
    discount: 50,
    isHotDeal: true,
  },
  {
    id: "trav2",
    title: "Marriott 3-Night Stay for 2",
    price: 299,
    originalPrice: 450,
    merchant: "Marriott.com",
    imageUrl: baseImage("trav2"),
    postedAt: "2026-01-04T09:30:00",
    category: "Travel Deals",
    url: "#",
    discount: 34,
  },
  {
    id: "trav3",
    title: "Hertz Rental Car 7-Day Pass",
    price: 149,
    originalPrice: 249,
    merchant: "Hertz.com",
    imageUrl: baseImage("trav3"),
    postedAt: "2026-01-04T09:00:00",
    category: "Travel Deals",
    url: "#",
    discount: 40,
    isHotDeal: true,
  },
  {
    id: "trav4",
    title: "Disney World 2-Day Park Hopper",
    price: 229,
    originalPrice: 299,
    merchant: "Disney.com",
    imageUrl: baseImage("trav4"),
    postedAt: "2026-01-04T08:30:00",
    category: "Travel Deals",
    url: "#",
    discount: 23,
  },
  {
    id: "trav5",
    title: "Southwest Airlines 50% Off Companion",
    price: 0,
    originalPrice: 0,
    merchant: "Southwest.com",
    imageUrl: baseImage("trav5"),
    postedAt: "2026-01-04T08:00:00",
    category: "Travel Deals",
    url: "#",
    description: "Book companion fare at 50% off",
    isHotDeal: true,
  },
];

/**
 * Quick coupons (high discount codes)
 */
export const QUICK_COUPONS: Deal[] = [
  {
    id: "qc1",
    title: "10% Off Amazon Entire Order",
    price: 0,
    originalPrice: 0,
    merchant: "Amazon.com",
    imageUrl: baseImage("qc1"),
    postedAt: "2026-01-04T10:00:00",
    category: "Quick Coupons",
    url: "#",
    discount: 10,
    description: "Coupon code: SAVE10",
    isHotDeal: true,
  },
  {
    id: "qc2",
    title: "Free Shipping on Orders Over $35",
    price: 0,
    originalPrice: 0,
    merchant: "Target",
    imageUrl: baseImage("qc2"),
    postedAt: "2026-01-04T09:30:00",
    category: "Quick Coupons",
    url: "#",
    description: "Free shipping on $35+",
  },
  {
    id: "qc3",
    title: "25% Off First Order",
    price: 0,
    originalPrice: 0,
    merchant: "Wayfair",
    imageUrl: baseImage("qc3"),
    postedAt: "2026-01-04T09:00:00",
    category: "Quick Coupons",
    url: "#",
    discount: 25,
    isHotDeal: true,
  },
  {
    id: "qc4",
    title: "Buy 2 Get 1 Free",
    price: 0,
    originalPrice: 0,
    merchant: "Barnes & Noble",
    imageUrl: baseImage("qc4"),
    postedAt: "2026-01-04T08:45:00",
    category: "Quick Coupons",
    url: "#",
    description: "Buy 2 books, get 1 free",
  },
  {
    id: "qc5",
    title: "15% Off Your Order",
    price: 0,
    originalPrice: 0,
    merchant: "Nordstrom",
    imageUrl: baseImage("qc5"),
    postedAt: "2026-01-04T08:00:00",
    category: "Quick Coupons",
    url: "#",
    discount: 15,
    isHotDeal: true,
  },
];
